import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,mutate,ranking} from '../logic.mjs';
const students=[{id:'1',name:'A'},{id:'2',name:'B'},{id:'3',name:'C'}];
const marks=[20,20,15,15,10,10,10];
test('a claimed name cannot be claimed by another device; releasing keeps scores',()=>{const s=initialState();mutate(s,{type:'claim',id:'girdhar',token:'a'},students);assert.throws(()=>mutate(s,{type:'claim',id:'girdhar',token:'b'},students));mutate(s,{type:'score',id:'girdhar',token:'a',student:'1',marks},students);mutate(s,{type:'release',id:'girdhar'},students);assert.deepEqual(s.scores.girdhar['1'],marks);assert.throws(()=>mutate(s,{type:'score',id:'girdhar',token:'a',student:'2',marks},students));});
test('rejects missing, fractional, negative and over-limit marks',()=>{const s=initialState();mutate(s,{type:'claim',id:'girdhar',token:'a'},students);for(const invalid of [[],[21,...marks.slice(1)],[-1,...marks.slice(1)],[1.5,...marks.slice(1)]])assert.throws(()=>mutate(s,{type:'score',id:'girdhar',token:'a',student:'1',marks:invalid},students));});
test('upserts edits, waits for all judges, locks final results and ties share rank',()=>{const s=initialState();for(const j of s.judges){mutate(s,{type:'claim',id:j.id,token:j.id},students);for(const student of students){const score=student.id==='3'?marks.map(n=>n-1):marks;mutate(s,{type:'score',id:j.id,token:j.id,student:student.id,marks:score},students);}}assert.equal(s.finalized,true);const results=ranking(s,students);assert.deepEqual(results.map(s=>s.rank),[1,1,3]);assert.equal(results[0].total,300);assert.equal(results[0].average,100);assert.throws(()=>mutate(s,{type:'score',id:'girdhar',token:'girdhar',student:'1',marks},students));assert.throws(()=>mutate(s,{type:'add',id:'new',name:'New judge'},students));});
test('edits overwrite a previous score instead of creating a duplicate',()=>{const s=initialState();mutate(s,{type:'claim',id:'girdhar',token:'a'},students);mutate(s,{type:'score',id:'girdhar',token:'a',student:'1',marks},students);mutate(s,{type:'score',id:'girdhar',token:'a',student:'1',marks:marks.map(n=>n-1)},students);assert.equal(Object.keys(s.scores.girdhar).length,1);assert.equal(s.finalized,false);});
